### ISSUE TITLE
.html.tmp files

### ISSUE THREAD

**Issue by mikesteele81** [alejandro-alzate/love2doc#1]
Thanks for publishing this! I noticed that most of the content appears as .html.tmp files in the file system. Is this expected and intentional? I discovered that I can rename these to .html in order to open them with a web browser.

**Comment by alejandro-alzate** [comment]
No, sadly this is not inteded since the web crawler that i use is supposed to rename them, thanks for letting me know! Maybe i'll add the .gitignore exception. but are the .tmp files fully functional? does them redirect to a local file? if the link back to the official website maybe is that is why the crawler keeps them as tmp until it gets the time to convert the links to a local relative file.

Also i'll do a big update once v12 gets out, i've holding on just because i never expected someone getting use of it, but your heads up encourages me to do snapshot more frequently.

**Comment by alejandro-alzate** [comment]
Update: now the repo is getting an update
Automated readme and such!
as of writing this is archiving the 11.5 version

**Comment by alejandro-alzate** [comment]
the repo is up to date, you may check it out now
